name: Web3 bank frontend work flow

on:
  push:
    branches:
      - master

jobs:
  setting-up-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checking version
        uses: actions/checkout@v3
        with:
          node-version: "18"

      - name: Checking version
        uses: actions/setup-node@v3

      - name: Installing dependencies
        run: npm ci

      - name: build the app
        run: npm run test-all
